/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-97116-g8d019dbc5b-ffmpeg-windows-build-helpers"
#endif /* AVUTIL_FFVERSION_H */
